CREATE TABLE "MEMBER" (
	"ID"	VARCHAR2(20)		NULL,
	"NICKNAME"	VARCHAR2(15)		NULL,
	"PASSWORD"	VARCHAR2(10)		NULL,
	"EMAIL"	VARCHAR2(50)		NULL,
	"ADDRESS"	VARCHAR2(90)		NULL,
	"ALERT_CNT"	NUMBER		NULL,
	"IS_ADMIN"	NUMBER		NULL
);

CREATE TABLE "MESSAGE" (
	"MSG_SEQ"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NULL,
	"MSG_CONTENTS"	VARCHAR2(200)		NULL,
	"MSG_DATE"	DATE		NULL,
	"GET_ID"	VARCHAR2(20)		NULL
);

CREATE TABLE "COMMENT" (
	"COM_SEQ"	NUMBER		NULL,
	"COM_DATE"	DATE		NULL,
	"COM_CONTENTS"	VARCHAR2(1000)		NULL,
	"ID"	VARCHAR2(20)		NULL,
	"POST_NO"	NUMBER		NULL
);

CREATE TABLE "SALES_POST" (
	"POST_NO"	NUMBER		NULL,
	"POST_TITLE"	VARCHAR2(60)		NULL,
	"POST_PRICE"	NUMBER		NULL,
	"POST_CONTENTS"	VARCHAR2(2000)		NULL,
	"POST_ADDRESS"	VARCHAR2(30)		NULL,
	"POST_YN"	VARCHAR2(1)		NULL,
	"POST_DATE"	DATE		NULL,
	"POST_TAGS"	VARCHAR2(200)		NULL,
	"ID"	VARCHAR2(20)		NULL,
	"HIT"	NUMBER		NULL,
	"POST_CODE"	VARCHAR2(2)		NULL
);

CREATE TABLE "IMAGES" (
	"FILE_SEQ"	NUMBER		NOT NULL,
	"ORIGINAL_FILENAME"	VARCHAR2(100)		NULL,
	"RENAME_FILENAME"	VARCHAR2(100)		NULL,
	"FILE_DATE"	DATE		NULL,
	"FILE_PATH"	VARCHAR2(100)		NULL,
	"POST_NO"	NUMBER		NULL
);

CREATE TABLE "PAYMENT" (
	"PAYMT_SEQ"	NUMBER		NOT NULL,
	"PAYMT_STATUS"	VARCHAR2(20)		NULL,
	"PAYMT_METHOD"	VARCHAR2(12)		NULL,
	"PRICE"	NUMBER		NULL,
	"PAYMT_DATE"	DATE		NULL,
	"MSHIP_GRADE"	NUMBER		NULL
);

CREATE TABLE "SCRAP_SALES" (
	"POST_NO"	NUMBER		NULL,
	"SCRAP_CNT"	NUMBER		NULL,
	"ID"	VARCHAR2(20)		NULL
);

CREATE TABLE "MEMBERSHIP" (
	"MSHIP_GRADE"	NUMBER		NULL,
	"MSHIP_DATE"	NUMBER		NULL,
	"MSHIP_PRICE"	NUMBER		NULL
);

CREATE TABLE "MSHIPDATA" (
	"MSHIP_SEQ"	NUMBER		NOT NULL,
	"MSHIP_START"	DATE		NULL,
	"MSHIP_YN"	VARCHAR2(1)		NOT NULL,
	"MSHIP_END"	DATE		NULL,
	"MSHIP_GRADE"	NUMBER		NULL,
	"ID"	VARCHAR2(20)		NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MSG_SEQ",
	"ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COM_SEQ"
);

ALTER TABLE "SALES_POST" ADD CONSTRAINT "PK_SALES_POST" PRIMARY KEY (
	"POST_NO"
);

ALTER TABLE "IMAGES" ADD CONSTRAINT "PK_IMAGES" PRIMARY KEY (
	"FILE_SEQ"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAYMT_SEQ"
);

ALTER TABLE "SCRAP_SALES" ADD CONSTRAINT "PK_SCRAP_SALES" PRIMARY KEY (
	"POST_NO"
);

ALTER TABLE "MEMBERSHIP" ADD CONSTRAINT "PK_MEMBERSHIP" PRIMARY KEY (
	"MSHIP_GRADE"
);

ALTER TABLE "MSHIPDATA" ADD CONSTRAINT "PK_MSHIPDATA" PRIMARY KEY (
	"MSHIP_SEQ"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_MEMBER_TO_MESSAGE_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "SCRAP_SALES" ADD CONSTRAINT "FK_SALES_POST_TO_SCRAP_SALES_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "SALES_POST" (
	"POST_NO"
);

